-- Rest of Year Coverage (April through December)
-- Note: April 1, May 1, August 1, October 1, December 1 already have extensive coverage from new_history.csv
USE history_db;

-- April (skipping April 1 which has 148 events)
INSERT INTO events (year, month, day, title, description, category) VALUES
(1513, 4, 2, 'Ponce de León discovers Florida', 'Spanish explorer reaches Florida coast', 'Exploration'),
(1982, 4, 2, 'Falklands War begins', 'Argentina invades Falkland Islands', 'Military'),
(1948, 4, 3, 'Marshall Plan signed', 'Economic recovery plan for Europe enacted', 'Politics'),
(1974, 4, 3, '1974 Super Outbreak', 'Largest tornado outbreak in US history begins', 'Disasters'),
(1968, 4, 4, 'Martin Luther King Jr. assassinated', 'Civil rights leader shot in Memphis', 'Politics'),
(1949, 4, 4, 'NATO formed', 'North Atlantic Treaty signed', 'Politics'),
(1614, 4, 5, 'Pocahontas marries John Rolfe', 'Native American princess weds English colonist', 'Society'),
(1992, 4, 5, 'Siege of Sarajevo begins', 'Bosnian War siege starts', 'Military'),
(1896, 4, 6, 'First modern Olympics', 'Games begin in Athens, Greece', 'Sports'),
(1917, 4, 6, 'US enters World War I', 'Congress declares war on Germany', 'Military'),
(1948, 4, 7, 'WHO founded', 'World Health Organization established', 'Politics'),
(1994, 4, 7, 'Rwandan genocide begins', 'Mass killings start in Rwanda', 'Disasters'),
(1820, 4, 8, 'Venus de Milo discovered', 'Ancient Greek statue found', 'Archaeology'),
(2013, 4, 8, 'Margaret Thatcher dies', 'Former British PM dies at 87', 'Politics'),
(1865, 4, 9, 'Civil War ends', 'Robert E. Lee surrenders at Appomattox', 'Military'),
(2003, 4, 9, 'Baghdad falls', 'US forces capture Iraqi capital', 'Military'),
(1912, 4, 10, 'Titanic leaves port', 'RMS Titanic departs Southampton', 'History'),
(1972, 4, 10, 'Biological Weapons Convention', 'Treaty banning biological weapons signed', 'Politics'),
(1961, 4, 11, 'Eichmann trial begins', 'Nazi war criminal tried in Jerusalem', 'Politics'),
(1968, 4, 11, 'Civil Rights Act of 1968', 'Fair Housing Act signed by LBJ', 'Politics'),
(1861, 4, 12, 'American Civil War begins', 'Confederate forces fire on Fort Sumter', 'Military'),
(1961, 4, 12, 'Yuri Gagarin first human in space', 'Soviet cosmonaut orbits Earth', 'Space'),
(1743, 4, 13, 'Thomas Jefferson born', 'Future US president born in Virginia', 'Births'),
(1970, 4, 13, 'Apollo 13 oxygen tank explodes', 'Moon mission endangered', 'Space'),
(1865, 4, 16, 'Lincoln dies', 'President Abraham Lincoln dies from gunshot', 'Politics'),
(2007, 4, 16, 'Virginia Tech shooting', 'Campus massacre kills 32', 'Disasters'),
(1521, 4, 17, 'Martin Luther excommunicated', 'Protestant reformer declared heretic', 'Religion'),
(1975, 4, 17, 'Cambodian genocide begins', 'Khmer Rouge captures Phnom Penh', 'Politics'),
(1775, 4, 19, 'American Revolutionary War begins', 'Battles of Lexington and Concord', 'Military'),
(1995, 4, 19, 'Oklahoma City bombing', 'Domestic terrorist attacks federal building', 'Terrorism'),
(1889, 4, 20, 'Adolf Hitler born', 'Future Nazi dictator born in Austria', 'Births'),
(2010, 4, 20, 'Deepwater Horizon explosion', 'Oil rig explodes in Gulf of Mexico', 'Disasters'),
(-753, 4, 21, 'Rome founded', 'Romulus establishes city of Rome (traditional date)', 'History'),
(1918, 4, 22, 'Red Baron shot down', 'German ace Manfred von Richthofen killed', 'Military'),
(1970, 4, 22, 'First Earth Day', 'Environmental movement celebrates first Earth Day', 'Society'),
(1516, 4, 23, 'Bavaria adopts beer purity law', 'Reinheitsgebot beer law enacted', 'Society'),
(1564, 4, 23, 'William Shakespeare born', 'English playwright born in Stratford (traditional date)', 'Births'),
(1915, 4, 24, 'Armenian Genocide begins', 'Ottoman Empire begins mass killings', 'Disasters'),
(1990, 4, 24, 'Hubble Space Telescope launched', 'NASA launches orbital observatory', 'Space'),
(1974, 4, 26, 'Count Basie dies', 'Jazz musician dies at 79', 'Music'),
(1986, 4, 26, 'Chernobyl disaster', 'Nuclear reactor explodes in Soviet Ukraine', 'Disasters'),
(1521, 4, 27, 'Magellan killed', 'Portuguese explorer killed in Philippines', 'Exploration'),
(1994, 4, 27, 'South African elections', 'First multi-racial elections held', 'Politics'),
(1945, 4, 28, 'Mussolini executed', 'Italian dictator killed by partisans', 'Politics'),
(1967, 4, 28, 'Muhammad Ali refuses draft', 'Boxer refuses military service', 'Sports'),
(1429, 4, 29, 'Joan of Arc enters Orléans', 'French heroine lifts siege', 'Military'),
(1992, 4, 29, 'LA riots begin', 'Rodney King verdict sparks riots', 'Society'),
(1945, 4, 30, 'Adolf Hitler commits suicide', 'Nazi leader dies in Berlin bunker', 'Politics'),
(1975, 4, 30, 'Fall of Saigon', 'Vietnam War ends with Communist victory', 'Military');

-- May (skipping May 1 which has 57 events)
INSERT INTO events (year, month, day, title, description, category) VALUES
(1536, 5, 2, 'Anne Boleyn arrested', 'Queen of England charged with treason', 'Politics'),
(2011, 5, 2, 'Osama bin Laden killed', 'Al-Qaeda leader killed by US forces', 'Military'),
(1791, 5, 3, 'Poland adopts constitution', 'First modern European constitution', 'Politics'),
(1979, 5, 3, 'Margaret Thatcher becomes PM', 'First female UK Prime Minister', 'Politics'),
(1776, 5, 4, 'Rhode Island independence', 'First colony to declare independence', 'Politics'),
(1970, 5, 4, 'Kent State shootings', 'National Guard kills four students', 'Society'),
(1862, 5, 5, 'Cinco de Mayo', 'Mexican army defeats French at Puebla', 'Military'),
(1821, 5, 5, 'Napoleon dies', 'French emperor dies in exile', 'Politics'),
(1889, 5, 7, 'Eiffel Tower opens', 'Paris landmark opens to public', 'Architecture'),
(1945, 5, 7, 'Germany surrenders', 'Nazi Germany unconditionally surrenders', 'Military'),
(1945, 5, 8, 'V-E Day', 'Victory in Europe Day celebrated', 'Military'),
(1980, 5, 8, 'WHO declares smallpox eradicated', 'First disease eradicated by vaccination', 'Medicine'),
(1960, 5, 9, 'Birth control pill approved', 'FDA approves first oral contraceptive', 'Medicine'),
(1978, 5, 9, 'Aldo Moro found dead', 'Italian PM killed by Red Brigades', 'Politics'),
(1940, 5, 10, 'Winston Churchill becomes PM', 'Churchill replaces Chamberlain', 'Politics'),
(1994, 5, 10, 'Nelson Mandela inaugurated', 'First black South African president', 'Politics'),
(330, 5, 11, 'Constantinople becomes capital', 'Byzantine Empire capital established', 'Politics'),
(1997, 5, 11, 'Deep Blue defeats Kasparov', 'Computer wins chess match', 'Technology'),
(1949, 5, 12, 'Berlin Blockade ends', 'Soviet blockade lifted', 'Politics'),
(2008, 5, 12, 'Sichuan earthquake', 'Magnitude 7.9 quake kills 87,000 in China', 'Disasters'),
(1940, 5, 13, 'Winston Churchill We shall fight speech', 'Famous wartime speech', 'Politics'),
(1981, 5, 13, 'Pope John Paul II shot', 'Assassination attempt in St Peters Square', 'Politics'),
(1948, 5, 14, 'Israel declares independence', 'State of Israel established', 'Politics'),
(1610, 5, 14, 'Henry IV of France assassinated', 'French king killed', 'Politics'),
(1905, 5, 15, 'Las Vegas founded', 'Nevada city established', 'Society'),
(1972, 5, 15, 'George Wallace shot', 'Alabama governor paralyzed in assassination attempt', 'Politics'),
(1929, 5, 16, 'First Academy Awards', 'Oscars ceremony held in Hollywood', 'Entertainment'),
(1975, 5, 16, 'First woman climbs Everest', 'Junko Tabei reaches summit', 'Sports'),
(1954, 5, 17, 'Brown v. Board of Education', 'Supreme Court bans school segregation', 'Politics'),
(1990, 5, 17, 'WHO removes homosexuality from disease list', 'Historic medical decision', 'Society'),
(1804, 5, 18, 'Napoleon becomes Emperor', 'Bonaparte crowned Emperor of France', 'Politics'),
(1980, 5, 18, 'Mount St. Helens erupts', 'Volcanic eruption kills 57 in Washington', 'Disasters'),
(1536, 5, 19, 'Anne Boleyn executed', 'Queen of England beheaded', 'Politics'),
(1962, 5, 19, 'Marilyn Monroe sings to JFK', 'Happy Birthday Mr. President performance', 'Entertainment'),
(325, 5, 20, 'First Council of Nicaea', 'First ecumenical council convenes', 'Religion'),
(1927, 5, 20, 'Lindbergh lands in Paris', 'First solo transatlantic flight completed', 'Aviation'),
(1881, 5, 21, 'American Red Cross founded', 'Clara Barton establishes organization', 'Society'),
(1991, 5, 21, 'Rajiv Gandhi assassinated', 'Former Indian PM killed', 'Politics'),
(1455, 5, 22, 'Wars of the Roses begin', 'English civil war starts', 'Military'),
(2011, 5, 22, 'Joplin tornado', 'EF5 tornado kills 158 in Missouri', 'Disasters'),
(1844, 5, 24, 'First telegraph message', 'Samuel Morse sends What hath God wrought', 'Technology'),
(1941, 5, 24, 'Bismarck sinks HMS Hood', 'German battleship sinks British ship', 'Military'),
(1787, 5, 25, 'Constitutional Convention begins', 'US Constitution drafting starts', 'Politics'),
(1977, 5, 25, 'Star Wars released', 'George Lucas film debuts', 'Entertainment'),
(1647, 5, 26, 'Alse Young executed', 'First witch execution in American colonies', 'Society'),
(1868, 5, 26, 'President Andrew Johnson acquitted', 'Senate fails to remove president', 'Politics'),
(1937, 5, 27, 'Golden Gate Bridge opens', 'San Francisco landmark dedicated', 'Architecture'),
(1941, 5, 27, 'Bismarck sunk', 'British forces sink German battleship', 'Military'),
(1934, 5, 28, 'Dionne quintuplets born', 'First quintuplets to survive infancy', 'Medicine'),
(1961, 5, 28, 'Amnesty International founded', 'Human rights organization established', 'Society'),
(1453, 5, 29, 'Constantinople falls', 'Ottoman Empire captures Byzantine capital', 'Military'),
(1953, 5, 29, 'Edmund Hillary climbs Everest', 'First confirmed ascent of Mount Everest', 'Sports'),
(1431, 5, 30, 'Joan of Arc executed', 'French heroine burned at stake', 'Politics'),
(1958, 5, 30, 'Memorial Day Massacre', 'Unknown soldiers from WWII and Korea honored', 'Military'),
(1578, 5, 31, 'King Henry III lays first stone of Pont Neuf', 'Paris bridge construction begins', 'Architecture'),
(1970, 5, 31, 'Peru earthquake', 'Magnitude 7.9 quake kills 70,000', 'Disasters');

-- Continue with remaining months...
SELECT 'April-May events added!' AS Status;
SELECT COUNT(*) AS total_events FROM events;
SELECT COUNT(DISTINCT CONCAT(month,'-',day)) AS dates_covered FROM events;
