-- Complete Year Coverage: June through December
-- Adding 2-3 events for each remaining uncovered date
USE history_db;

-- June
INSERT INTO events (year, month, day, title, description, category) VALUES
-- June 2-5 (June 1 skipped - no existing data shown, adding anyway)
(1953, 6, 2, 'Queen Elizabeth II crowned', 'Coronation ceremony at Westminster Abbey', 'Politics'),
(1946, 6, 2, 'Italy becomes republic', 'Referendum abolishes monarchy', 'Politics'),
(1940, 6, 3, 'Dunkirk evacuation ends', 'Last troops evacuated from France', 'Military'),
(1963, 6, 3, 'Pope John XXIII dies', 'Catholic pope dies in Vatican', 'Religion'),
(1919, 6, 4, 'Women suffrage passes Congress', '19th Amendment approved', 'Politics'),
(1942, 6, 4, 'Battle of Midway begins', 'Turning point in Pacific War', 'Military'),
(1944, 6, 5, 'D-Day preparation', 'Final preparations for Normandy invasion', 'Military'),
(1967, 6, 5, 'Six-Day War begins', 'Israel conflicts with Arab nations', 'Military'),
-- June 6 already covered (D-Day)
(1799, 6, 7, 'Patrick Henry dies', 'American Founding Father dies', 'Politics'),
(1942, 6, 7, 'Battle of Midway continues', 'US Navy defeats Japanese fleet', 'Military'),
(632, 6, 8, 'Muhammad dies', 'Islamic prophet dies in Medina', 'Religion'),
(1966, 6, 8, 'Gemini 9 launched', 'NASA spacecraft reaches orbit', 'Space'),
(68, 6, 9, 'Nero commits suicide', 'Roman Emperor dies', 'Politics'),
(1973, 6, 9, 'Secretariat wins Triple Crown', 'Racehorse wins Belmont Stakes', 'Sports'),
(1967, 6, 10, 'Six-Day War ends', 'Israel achieves military victory', 'Military'),
(1942, 6, 10, 'Lidice massacre', 'Nazis destroy Czech village', 'Military'),
(1963, 6, 11, 'Buddhist crisis in Vietnam', 'Thích Quảng Đức self-immolation', 'Politics'),
(1776, 6, 11, 'Continental Congress appoints drafting committee', 'Declaration of Independence committee formed', 'Politics'),
-- June 12 already covered
(-323, 6, 13, 'Alexander the Great dies', 'Macedonian conqueror dies in Babylon', 'Military'),
(1971, 6, 13, 'Pentagon Papers published', 'NY Times publishes classified documents', 'Politics'),
(1777, 6, 14, 'Stars and Stripes adopted', 'US flag design approved', 'Politics'),
(1982, 6, 14, 'Falklands War ends', 'Argentina surrenders to Britain', 'Military'),
(1215, 6, 15, 'Magna Carta sealed', 'King John signs charter at Runnymede', 'Politics'),
(1844, 6, 15, 'Rubber vulcanization patented', 'Charles Goodyear patents process', 'Technology'),
(1963, 6, 16, 'Valentina Tereshkova in space', 'First woman in space', 'Space'),
(1858, 6, 16, 'Lincoln House Divided speech', 'Famous speech in Springfield', 'Politics'),
(1579, 6, 17, 'Francis Drake claims California', 'English explorer claims New Albion', 'Exploration'),
(1972, 6, 17, 'Watergate break-in', 'Burglars caught at DNC headquarters', 'Politics'),
-- June 18 already covered
(1865, 6, 19, 'Juneteenth', 'Slavery ends in Texas', 'Politics'),
(1953, 6, 19, 'Rosenbergs executed', 'Convicted spies put to death', 'Politics'),
(1789, 6, 20, 'Tennis Court Oath', 'French Revolution milestone', 'Politics'),
(1963, 6, 20, 'Hotline established', 'US-Soviet communication link created', 'Politics'),
(1788, 6, 21, 'Constitution ratified', 'New Hampshire makes it official', 'Politics'),
(1964, 6, 21, 'Civil rights workers murdered', 'Three activists killed in Mississippi', 'Society'),
-- June 22-23 already covered
(1947, 6, 24, 'First flying saucer sighting', 'Kenneth Arnold reports UFO', 'Society'),
(1948, 6, 24, 'Berlin Blockade begins', 'Soviets cut off West Berlin', 'Politics'),
(1876, 6, 25, 'Battle of Little Bighorn', 'Custer\'s Last Stand', 'Military'),
(1950, 6, 25, 'Korean War begins', 'North Korea invades South', 'Military'),
(1945, 6, 26, 'UN Charter signed', 'United Nations officially created', 'Politics'),
(1997, 6, 26, 'Harry Potter published', 'First book released in UK', 'Literature'),
(1950, 6, 27, 'US enters Korean War', 'Truman orders forces to Korea', 'Military'),
(1969, 6, 27, 'Stonewall riots begin', 'Gay rights movement milestone', 'Society'),
-- June 28 already covered
(1613, 6, 29, 'Globe Theatre burns', 'Shakespeare\'s theatre destroyed', 'Arts'),
(1974, 6, 29, 'First woman Episcopal priest', 'Historic ordination in Philadelphia', 'Religion'),
(1908, 6, 30, 'Tunguska event', 'Massive explosion in Siberia', 'Disasters'),
(1997, 6, 30, 'Hong Kong returned to China', 'British colony transferred to PRC', 'Politics');

-- July
INSERT INTO events (year, month, day, title, description, category) VALUES
(1863, 7, 1, 'Battle of Gettysburg begins', 'Major Civil War battle starts', 'Military'),
(1997, 7, 1, 'Hong Kong handover', 'Britain returns Hong Kong to China', 'Politics'),
(1964, 7, 2, 'Civil Rights Act signed', 'LBJ signs landmark legislation', 'Politics'),
(1776, 7, 2, 'Continental Congress votes for independence', 'Resolution passed', 'Politics'),
(1844, 7, 3, 'Last great auk killed', 'Species driven to extinction', 'Society'),
(1988, 7, 3, 'USS Vincennes shoots down airliner', 'Iran Air Flight 655 destroyed', 'Military'),
-- July 4 covered
(1943, 7, 5, 'Battle of Kursk begins', 'Largest tank battle in history', 'Military'),
(1996, 7, 5, 'Dolly the sheep cloned', 'First mammal cloned from adult cell', 'Science'),
(1885, 7, 6, 'Louis Pasteur vaccinates for rabies', 'First rabies vaccine administered', 'Medicine'),
(1988, 7, 6, 'Piper Alpha disaster', 'Oil platform explosion kills 167', 'Disasters'),
-- July 7 covered
(1889, 7, 8, 'Wall Street Journal first published', 'Financial newspaper debuts', 'Business'),
(1947, 7, 8, 'Roswell incident', 'Alleged UFO crash in New Mexico', 'Society'),
(1877, 7, 9, 'First Wimbledon Championship', 'Tennis tournament begins', 'Sports'),
(1816, 7, 9, 'Argentina declares independence', 'Independence from Spain', 'Politics'),
(1509, 7, 10, 'John Calvin born', 'Protestant reformer born', 'Religion'),
(1962, 7, 10, 'Telstar satellite launched', 'First transatlantic TV broadcast', 'Technology'),
(1804, 7, 11, 'Burr-Hamilton duel', 'Aaron Burr kills Alexander Hamilton', 'Politics'),
(1979, 7, 11, 'Skylab falls', 'Space station re-enters atmosphere', 'Space'),
(1862, 7, 12, 'Medal of Honor authorized', 'US military decoration created', 'Military'),
(1975, 7, 12, 'São Tomé and Príncipe independence', 'African nation gains independence', 'Politics'),
(1930, 7, 13, 'First World Cup Final', 'Uruguay wins inaugural tournament', 'Sports'),
(1977, 7, 13, 'New York City blackout', 'Massive power outage', 'Disasters'),
-- July 14 covered
(1806, 7, 15, 'Pike Expedition begins', 'Zebulon Pike explores American West', 'Exploration'),
(1965, 7, 15, 'Mariner 4 reaches Mars', 'First spacecraft to photograph Mars', 'Space'),
(622, 7, 16, 'Islamic calendar begins', 'Hijra marks year 1', 'Religion'),
(1945, 7, 16, 'Trinity test', 'First atomic bomb detonated', 'Military'),
(180, 7, 17, 'Twelve Martyrs of Scillium executed', 'Early Christian martyrs', 'Religion'),
(1975, 7, 17, 'Apollo-Soyuz Test Project', 'US and Soviet spacecraft dock', 'Space'),
(64, 7, 18, 'Great Fire of Rome begins', 'Rome burns for nine days', 'Disasters'),
(1936, 7, 18, 'Spanish Civil War begins', 'Military uprising against Republic', 'Military'),
(1799, 7, 19, 'Rosetta Stone found', 'Key to Egyptian hieroglyphs discovered', 'Archaeology'),
(1848, 7, 19, 'Seneca Falls Convention', 'Women\'s rights convention', 'Society'),
-- July 20 covered
(1861, 7, 21, 'First Battle of Bull Run', 'First major Civil War battle', 'Military'),
(1969, 7, 21, 'Armstrong walks on Moon', 'First steps on lunar surface', 'Space'),
(1099, 7, 22, 'First Crusade ends', 'Jerusalem captured by Crusaders', 'Military'),
(1933, 7, 22, 'Wiley Post flies solo around world', 'First solo circumnavigation flight', 'Aviation'),
(1829, 7, 23, 'Typewriter patented', 'William Austin Burt invents typographer', 'Technology'),
(1952, 7, 23, 'Egyptian Revolution', 'Free Officers overthrow King Farouk', 'Politics'),
(1911, 7, 24, 'Machu Picchu revealed', 'Hiram Bingham reaches Inca ruins', 'Archaeology'),
(1969, 7, 24, 'Apollo 11 returns', 'Moon mission splashes down', 'Space'),
(1909, 7, 25, 'Blériot flies English Channel', 'First airplane crossing of Channel', 'Aviation'),
(1943, 7, 25, 'Mussolini arrested', 'Italian dictator deposed', 'Politics'),
(1847, 7, 26, 'Liberia declares independence', 'First African republic', 'Politics'),
(1953, 7, 26, 'Cuban Revolution begins', 'Castro attacks Moncada Barracks', 'Politics'),
(1775, 7, 27, 'U.S. Post Office established', 'Continental Congress creates postal system', 'Politics'),
(1953, 7, 27, 'Korean War armistice', 'Fighting ends on Korean Peninsula', 'Military'),
-- July 28 covered
(1588, 7, 29, 'Spanish Armada defeated', 'English fleet defeats Spanish invasion', 'Military'),
(1981, 7, 29, 'Charles and Diana marry', 'Royal wedding in London', 'Society'),
(1619, 7, 30, 'First representative assembly', 'Virginia House of Burgesses meets', 'Politics'),
(1956, 7, 30, 'In God We Trust', 'US national motto adopted', 'Politics'),
(1498, 7, 31, 'Columbus discovers Trinidad', 'Explorer reaches Caribbean island', 'Exploration'),
(1964, 7, 31, 'Ranger 7 photographs Moon', 'Spacecraft images lunar surface', 'Space');

-- August (August 1 already has 47 events)
INSERT INTO events (year, month, day, title, description, category) VALUES
(-216, 8, 2, 'Battle of Cannae', 'Hannibal defeats Romans', 'Military'),
(1990, 8, 2, 'Iraq invades Kuwait', 'Gulf War crisis begins', 'Military'),
(1492, 8, 3, 'Columbus sets sail', 'Explorer leaves Spain for Americas', 'Exploration'),
(1958, 8, 3, 'Nautilus crosses North Pole', 'Submarine passes under polar ice', 'Military'),
(70, 8, 4, 'Second Temple destroyed', 'Romans destroy Jewish temple', 'Religion'),
(1892, 8, 4, 'Lizzie Borden murders', 'Alleged axe murders in Massachusetts', 'Crime'),
(1962, 8, 5, 'Marilyn Monroe dies', 'American actress found dead', 'Entertainment'),
(1963, 8, 5, 'Nuclear Test Ban Treaty', 'US, UK, USSR sign treaty', 'Politics'),
(1945, 8, 6, 'Hiroshima bombed', 'First atomic bomb used in war', 'Military'),
(1965, 8, 6, 'Voting Rights Act signed', 'LBJ signs voting rights law', 'Politics'),
(1942, 8, 7, 'Battle of Guadalcanal begins', 'First major US offensive in Pacific', 'Military'),
(1998, 8, 7, 'US embassy bombings', 'Terrorists attack embassies in Africa', 'Terrorism'),
(1974, 8, 8, 'Nixon resigns', 'President announces resignation', 'Politics'),
(1942, 8, 8, 'Gandhi arrested', 'Quit India Movement leader jailed', 'Politics'),
(1945, 8, 9, 'Nagasaki bombed', 'Second atomic bomb dropped', 'Military'),
(1974, 8, 9, 'Gerald Ford becomes president', 'Ford sworn in after Nixon resignation', 'Politics'),
(1809, 8, 10, 'Ecuador independence', 'First cry of independence from Spain', 'Politics'),
(1977, 8, 10, 'Son of Sam arrested', 'Serial killer David Berkowitz captured', 'Crime'),
(-3114, 8, 11, 'Mayan calendar begins', 'Long Count calendar starts', 'History'),
(1999, 8, 11, 'Total solar eclipse', 'Last total eclipse of 20th century', 'Space'),
(1877, 8, 12, 'Asaph Hall discovers Deimos', 'Mars moon discovered', 'Space'),
(1908, 8, 12, 'Model T produced', 'First Ford Model T assembled', 'Business'),
(1961, 8, 13, 'Berlin Wall construction begins', 'East Germany closes border', 'Politics'),
(2004, 8, 13, 'Olympic Games in Athens', 'Summer Olympics return to Greece', 'Sports'),
(1945, 8, 14, 'V-J Day', 'Victory over Japan announced', 'Military'),
(1971, 8, 14, 'Bahrain independence', 'Persian Gulf nation gains independence', 'Politics'),
-- August 15 covered
(1977, 8, 16, 'Elvis Presley dies', 'King of Rock and Roll dies', 'Music'),
(1896, 8, 16, 'Gold discovered in Klondike', 'Yukon gold rush begins', 'History'),
(1945, 8, 17, 'Animal Farm published', 'George Orwell novel released', 'Literature'),
(1962, 8, 17, 'Peter Fechter shot', 'East German youth killed at Berlin Wall', 'Politics'),
(1587, 8, 18, 'Virginia Dare born', 'First English child born in Americas', 'History'),
(1920, 8, 18, '19th Amendment ratified', 'Women get right to vote in US', 'Politics'),
(14, 8, 19, 'Augustus dies', 'First Roman Emperor dies', 'Politics'),
(1991, 8, 19, 'Soviet coup attempt', 'Hardliners try to overthrow Gorbachev', 'Politics'),
(636, 8, 20, 'Battle of Yarmouk', 'Muslim forces defeat Byzantines', 'Military'),
(1968, 8, 20, 'Prague Spring crushed', 'Warsaw Pact invades Czechoslovakia', 'Military'),
(1911, 8, 21, 'Mona Lisa stolen', 'Leonardo painting taken from Louvre', 'Crime'),
(1959, 8, 21, 'Hawaii becomes 50th state', 'Hawaii admitted to Union', 'Politics'),
(1572, 8, 22, 'St. Bartholomew\'s Day Massacre begins', 'Catholics kill Huguenots in Paris', 'Religion'),
(1864, 8, 22, 'Geneva Convention signed', 'First Geneva Convention established', 'Politics'),
(79, 8, 23, 'Mount Vesuvius erupts', 'Pompeii and Herculaneum buried', 'Disasters'),
(1939, 8, 23, 'Molotov-Ribbentrop Pact', 'Nazi-Soviet non-aggression pact', 'Politics'),
-- August 24 covered
(1530, 8, 25, 'Battle of Mohács', 'Ottoman Turks defeat Hungary', 'Military'),
(1944, 8, 25, 'Liberation of Paris', 'Allied forces free French capital', 'Military'),
-- August 26 covered
(1883, 8, 27, 'Krakatoa erupts', 'Volcanic eruption heard 3,000 miles away', 'Disasters'),
(1928, 8, 27, 'Kellogg-Briand Pact', 'Treaty outlawing war signed', 'Politics'),
(1963, 8, 28, 'March on Washington', 'I Have a Dream speech delivered', 'Society'),
(2005, 8, 28, 'Hurricane Katrina landfall', 'Storm devastates Gulf Coast', 'Disasters'),
(1831, 8, 29, 'Faraday discovers electromagnetic induction', 'Key physics discovery', 'Science'),
(2005, 8, 29, 'Hurricane Katrina floods New Orleans', 'Levees fail, city flooded', 'Disasters'),
(1800, 8, 30, 'Gabriel Prosser rebellion', 'Slave rebellion in Virginia', 'History'),
(1983, 8, 30, 'Guion Bluford in space', 'First African American astronaut', 'Space'),
(1422, 8, 31, 'Battle of Arbedo', 'Swiss defeat Milan', 'Military'),
(1997, 8, 31, 'Princess Diana dies', 'British princess killed in Paris crash', 'Society');

-- September
INSERT INTO events (year, month, day, title, description, category) VALUES
-- September 1 covered
(-31, 9, 2, 'Battle of Actium', 'Octavian defeats Mark Antony', 'Military'),
(1945, 9, 2, 'World War II ends', 'Japan signs surrender aboard USS Missouri', 'Military'),
-- September 3 covered
(476, 9, 4, 'Fall of Western Roman Empire', 'Last emperor deposed', 'Politics'),
(1888, 9, 4, 'George Eastman patents camera', 'Kodak camera patented', 'Technology'),
(1774, 9, 5, 'First Continental Congress convenes', 'Colonial delegates meet in Philadelphia', 'Politics'),
(1972, 9, 5, 'Munich Olympics massacre', 'Palestinian terrorists kill Israeli athletes', 'Terrorism'),
-- September 6 covered
(1812, 9, 7, 'Battle of Borodino', 'Napoleon vs. Russia, bloodiest single day', 'Military'),
(1977, 9, 7, 'Panama Canal treaties signed', 'US agrees to transfer canal', 'Politics'),
(1504, 9, 8, 'Michelangelo\'s David unveiled', 'Renaissance masterpiece revealed', 'Arts'),
(1974, 9, 8, 'Gerald Ford pardons Nixon', 'President grants full pardon', 'Politics'),
(1776, 9, 9, 'United States named', 'Continental Congress adopts name', 'Politics'),
(1948, 9, 9, 'North Korea founded', 'Democratic People\'s Republic established', 'Politics'),
(1608, 9, 10, 'John Smith elected leader', 'Jamestown colony leader chosen', 'Politics'),
(1846, 9, 10, 'Elias Howe patents sewing machine', 'Revolutionary invention patented', 'Technology'),
-- September 11 covered
(1683, 9, 12, 'Battle of Vienna', 'Ottoman siege of Vienna lifted', 'Military'),
(1977, 9, 12, 'Steve Biko dies', 'South African anti-apartheid activist killed', 'Politics'),
(1759, 9, 13, 'Battle of Quebec', 'British defeat French in Canada', 'Military'),
(1993, 9, 13, 'Oslo Accords signed', 'Israeli-Palestinian peace agreement', 'Politics'),
(1814, 9, 14, 'Star-Spangled Banner written', 'Francis Scott Key writes national anthem', 'History'),
(1960, 9, 14, 'OPEC founded', 'Oil-producing countries form cartel', 'Economics'),
(1830, 9, 15, 'First steam locomotive race', 'Tom Thumb vs. horse-drawn car', 'Technology'),
(1963, 9, 15, 'Birmingham church bombing', 'KKK kills four girls in Alabama', 'Terrorism'),
(1620, 9, 16, 'Mayflower departs', 'Pilgrims leave Plymouth for America', 'Exploration'),
(1987, 9, 16, 'Montreal Protocol signed', 'Ozone layer protection treaty', 'Politics'),
(1787, 9, 17, 'Constitution signed', 'US Constitution signed in Philadelphia', 'Politics'),
(2011, 9, 17, 'Occupy Wall Street begins', 'Protest movement starts', 'Society'),
(1759, 9, 18, 'British capture Quebec', 'Decisive battle in French and Indian War', 'Military'),
(1947, 9, 18, 'CIA established', 'National Security Act creates CIA', 'Politics'),
(1356, 9, 19, 'Battle of Poitiers', 'English victory in Hundred Years War', 'Military'),
(1982, 9, 19, 'First emoticons', 'Scott Fahlman proposes :-)', 'Technology'),
(1519, 9, 20, 'Magellan expedition begins', 'First circumnavigation of globe starts', 'Exploration'),
(1973, 9, 20, 'Battle of the Sexes', 'Billie Jean King defeats Bobby Riggs', 'Sports'),
(1327, 9, 21, 'Edward II murdered', 'English king killed in captivity', 'Politics'),
(1981, 9, 21, 'Belize independence', 'Central American nation gains independence', 'Politics'),
(1862, 9, 22, 'Emancipation Proclamation issued', 'Lincoln announces slaves to be freed', 'Politics'),
(1980, 9, 22, 'Iran-Iraq War begins', 'Eight-year conflict starts', 'Military'),
(1846, 9, 23, 'Neptune discovered', 'Planet Neptune identified', 'Space'),
(1952, 9, 23, 'Nixon Checkers speech', 'VP candidate defends finances', 'Politics'),
(1789, 9, 24, 'Supreme Court created', 'Judiciary Act establishes Court', 'Politics'),
(1957, 9, 24, 'Little Rock Nine enter school', 'Federal troops enforce integration', 'Society'),
-- September 25 covered
(1580, 9, 26, 'Drake completes circumnavigation', 'Francis Drake returns to England', 'Exploration'),
(1983, 9, 26, 'Soviet nuclear false alarm', 'Stanislav Petrov prevents WWIII', 'Military'),
(1854, 9, 27, 'Arctic sinks', 'Steamship collision kills 300', 'Disasters'),
(1996, 9, 27, 'Taliban captures Kabul', 'Fundamentalists take Afghan capital', 'Politics'),
(-48, 9, 28, 'Pompey assassinated', 'Roman general killed in Egypt', 'Politics'),
(1995, 9, 28, 'Israeli PM Yitzhak Rabin assassinated', 'Peace advocate killed', 'Politics'),
(1938, 9, 29, 'Munich Agreement', 'Britain and France appease Hitler', 'Politics'),
(2008, 9, 29, 'Dow drops 777 points', 'Largest single-day stock drop', 'Economics'),
-- September 30 covered

-- October (October 1, 23 already covered)
INSERT INTO events (year, month, day, title, description, category) VALUES
(1187, 10, 2, 'Saladin captures Jerusalem', 'Muslim forces retake holy city', 'Military'),
(1950, 10, 2, 'Peanuts debuts', 'Charles Schulz comic strip first published', 'Entertainment'),
(1863, 10, 3, 'Lincoln proclaims Thanksgiving', 'National holiday established', 'Society'),
(1990, 10, 3, 'German reunification', 'East and West Germany reunited', 'Politics'),
(1957, 10, 4, 'Sputnik 1 launched', 'First artificial satellite', 'Space'),
(1993, 10, 4, 'Battle of Mogadishu', 'Black Hawk Down incident', 'Military'),
(1962, 10, 5, 'Dr. No released', 'First James Bond film', 'Entertainment'),
(2011, 10, 5, 'Steve Jobs dies', 'Apple co-founder dies at 56', 'Technology'),
(1927, 10, 6, 'The Jazz Singer premieres', 'First feature-length talkie', 'Entertainment'),
(1973, 10, 6, 'Yom Kippur War begins', 'Arab states attack Israel', 'Military'),
(1571, 10, 7, 'Battle of Lepanto', 'Christian fleet defeats Ottoman Turks', 'Military'),
(2001, 10, 7, 'War in Afghanistan begins', 'US invades after 9/11', 'Military'),
(1871, 10, 8, 'Great Chicago Fire begins', 'Fire destroys much of Chicago', 'Disasters'),
(1967, 10, 8, 'Che Guevara captured', 'Revolutionary caught in Bolivia', 'Politics'),
(1967, 10, 9, 'Che Guevara executed', 'Revolutionary killed in Bolivia', 'Politics'),
(1992, 10, 9, 'Meteorite hits car', 'Chevy Malibu struck in New York', 'Space'),
(732, 10, 10, 'Battle of Tours', 'Charles Martel defeats Umayyads', 'Military'),
(1973, 10, 10, 'Spiro Agnew resigns', 'VP resigns over corruption', 'Politics'),
(1138, 10, 11, 'Aleppo earthquake', 'Deadliest earthquake in history', 'Disasters'),
(1975, 10, 11, 'Saturday Night Live debuts', 'Comedy show first airs', 'Entertainment'),
-- October 12 covered
(54, 10, 13, 'Claudius poisoned', 'Roman Emperor killed by Agrippina', 'Politics'),
(1792, 10, 13, 'White House cornerstone', 'Foundation laid in Washington DC', 'Architecture'),
(1066, 10, 14, 'Battle of Hastings', 'Norman Conquest of England', 'Military'),
(1964, 10, 14, 'Martin Luther King wins Nobel Peace Prize', 'Civil rights leader honored', 'Politics'),
(1582, 10, 15, 'Gregorian calendar adopted', 'Calendar reform implemented', 'Society'),
(1917, 10, 15, 'Mata Hari executed', 'Spy shot by French firing squad', 'Military'),
-- October 16 covered
-- October 17 covered
(1898, 10, 18, 'US annexes Puerto Rico', 'Territory ceded by Spain', 'Politics'),
(1867, 10, 18, 'Alaska Purchase completed', 'US formally takes possession', 'Politics'),
-- October 19 covered
-- October 20 covered
-- October 21 covered
(1797, 10, 22, 'First parachute jump', 'André-Jacques Garnerin jumps from balloon', 'Technology'),
(1962, 10, 22, 'Cuban Missile Crisis', 'Kennedy addresses nation', 'Politics'),
(-42, 10, 24, 'Battle of Philippi', 'Brutus defeated, Roman Republic ends', 'Military'),
(1945, 10, 24, 'United Nations founded', 'UN Charter takes effect', 'Politics'),
(1415, 10, 25, 'Battle of Agincourt', 'English defeat French', 'Military'),
(1971, 10, 25, 'UN seats Communist China', 'PRC replaces Taiwan', 'Politics'),
(1863, 10, 26, 'Red Cross founded', 'International Committee established', 'Society'),
(1979, 10, 26, 'Park Chung-hee assassinated', 'South Korean president killed', 'Politics'),
(1962, 10, 27, 'Black Saturday', 'Cuban Missile Crisis peak', 'Politics'),
(2005, 10, 27, 'Paris riots begin', 'French suburbs erupt in violence', 'Society'),
(1886, 10, 28, 'Statue of Liberty dedicated', 'French gift unveiled in New York', 'Architecture'),
(1962, 10, 28, 'Cuban Missile Crisis ends', 'Khrushchev agrees to remove missiles', 'Politics'),
(1618, 10, 29, 'Walter Raleigh executed', 'Explorer beheaded in London', 'Politics'),
(1929, 10, 29, 'Black Tuesday', 'Stock market crash, Great Depression begins', 'Economics'),
(1922, 10, 30, 'Mussolini becomes PM', 'Fascists march on Rome', 'Politics'),
(1938, 10, 30, 'War of the Worlds broadcast', 'Orson Welles radio drama panics listeners', 'Entertainment'),
(1517, 10, 31, '95 Theses', 'Martin Luther begins Reformation', 'Religion'),
(1984, 10, 31, 'Indira Gandhi assassinated', 'Indian PM killed by bodyguards', 'Politics');

-- November
INSERT INTO events (year, month, day, title, description, category) VALUES
(1755, 11, 1, 'Lisbon earthquake', 'Massive quake destroys Portuguese capital', 'Disasters'),
(1952, 11, 1, 'Hydrogen bomb tested', 'US tests first thermonuclear weapon', 'Military'),
(1917, 11, 2, 'Balfour Declaration', 'Britain supports Jewish homeland', 'Politics'),
(1947, 11, 2, 'Howard Hughes Spruce Goose', 'Largest airplane flies once', 'Aviation'),
(1957, 11, 3, 'Laika in space', 'First animal in orbit', 'Space'),
(1979, 11, 3, 'Greensboro massacre', 'KKK kills civil rights protesters', 'Society'),
(1922, 11, 4, 'Tutankhamun tomb discovered', 'Howard Carter finds pharaoh\'s tomb', 'Archaeology'),
(2008, 11, 4, 'Barack Obama elected', 'First African American president', 'Politics'),
(1605, 11, 5, 'Gunpowder Plot foiled', 'Guy Fawkes caught trying to blow up Parliament', 'Politics'),
(1999, 11, 5, 'Dow closes above 11,000', 'Stock market milestone', 'Economics'),
(1860, 11, 6, 'Lincoln elected president', 'Abraham Lincoln wins election', 'Politics'),
(2001, 11, 6, 'Microsoft releases Xbox', 'Gaming console debuts', 'Technology'),
-- November 7 covered
(395, 11, 8, 'Roman Empire divides', 'Split into East and West', 'Politics'),
(1923, 11, 8, 'Beer Hall Putsch begins', 'Hitler\'s failed coup attempt', 'Politics'),
-- November 9 covered
(1871, 11, 10, 'Stanley finds Livingstone', 'Explorers meet in Tanzania', 'Exploration'),
(1982, 11, 10, 'Brezhnev dies', 'Soviet leader dies', 'Politics'),
(1918, 11, 11, 'World War I ends', 'Armistice signed at 11:11 am', 'Military'),
(1889, 11, 11, 'Washington becomes state', '42nd state admitted', 'Politics'),
(1954, 11, 12, 'Ellis Island closes', 'Immigration station shuts down', 'Society'),
(1990, 11, 12, 'Akihito enthroned', 'Japanese emperor officially enthroned', 'Politics'),
(1985, 11, 13, 'Nevado del Ruiz erupts', 'Colombian volcano kills 23,000', 'Disasters'),
(2015, 11, 13, 'Paris attacks', 'ISIS terrorists kill 130', 'Terrorism'),
(1851, 11, 14, 'Moby-Dick published', 'Herman Melville novel released', 'Literature'),
(1973, 11, 14, 'Princess Anne marries', 'British royal wedding', 'Society'),
(1926, 11, 15, 'NBC begins broadcasting', 'First national radio network', 'Technology'),
(2001, 11, 15, 'Xbox launched', 'Microsoft gaming console released', 'Technology'),
(1945, 11, 16, 'UNESCO founded', 'UN cultural organization established', 'Politics'),
(1974, 11, 16, 'Arecibo message sent', 'SETI message transmitted to space', 'Space'),
(1558, 11, 17, 'Elizabeth I becomes queen', 'English Queen begins reign', 'Politics'),
(1973, 11, 17, 'Nixon I am not a crook', 'President denies Watergate involvement', 'Politics'),
(1307, 11, 18, 'William Tell legend', 'Swiss folk hero shoots apple', 'History'),
(1978, 11, 18, 'Jonestown massacre', 'Mass suicide in Guyana kills 918', 'Disasters'),
(1863, 11, 19, 'Gettysburg Address', 'Lincoln delivers famous speech', 'Politics'),
(1969, 11, 19, 'Apollo 12 lands on Moon', 'Second manned lunar landing', 'Space'),
(1945, 11, 20, 'Nuremberg Trials begin', 'Nazi leaders face justice', 'Politics'),
(1962, 11, 20, 'Cuban Missile Crisis ends officially', 'Naval quarantine lifted', 'Politics'),
-- November 21 covered
-- November 22 covered
(1248, 11, 23, 'Conquest of Seville', 'Christians retake Spanish city', 'Military'),
(1971, 11, 23, 'D.B. Cooper hijacking', 'Skyjacker parachutes with ransom', 'Crime'),
(1859, 11, 24, 'Origin of Species published', 'Darwin\'s evolution theory released', 'Science'),
(1963, 11, 24, 'Lee Harvey Oswald killed', 'JFK assassin shot by Jack Ruby', 'Crime'),
(1491, 11, 25, 'Expulsion from Spain begins', 'Jews ordered to leave', 'Politics'),
(1973, 11, 25, 'Pinochet coup in Greece', 'Military junta takes power', 'Politics'),
(1922, 11, 26, 'Tutankhamun burial chamber', 'Carter opens tomb', 'Archaeology'),
(2008, 11, 26, 'Mumbai attacks', 'Terrorists attack Indian city', 'Terrorism'),
(1895, 11, 27, 'Nobel Prize established', 'Alfred Nobel\'s will creates prizes', 'Society'),
(1978, 11, 27, 'Moscone-Milk assassinations', 'San Francisco mayor and supervisor killed', 'Politics'),
(1520, 11, 28, 'Magellan enters Pacific', 'Explorer reaches ocean', 'Exploration'),
(1964, 11, 28, 'Mariner 4 launched', 'Spacecraft heads to Mars', 'Space'),
(1947, 11, 29, 'UN votes for Israel partition', 'Palestine divided', 'Politics'),
(1963, 11, 29, 'Trans-Canada Airlines Flight 831', 'Plane crash kills 118', 'Disasters'),
(1782, 11, 30, 'American Revolutionary War ends', 'Preliminary peace treaty signed', 'Politics'),
(1999, 11, 30, 'WTO protests in Seattle', 'Anti-globalization demonstrations', 'Society');

-- December (December 1 already has 86 events)
INSERT INTO events (year, month, day, title, description, category) VALUES
(1804, 12, 2, 'Napoleon crowned Emperor', 'Bonaparte crowns himself in Paris', 'Politics'),
(1942, 12, 2, 'Manhattan Project', 'First nuclear chain reaction', 'Science'),
(1967, 12, 3, 'First heart transplant', 'Christiaan Barnard performs surgery', 'Medicine'),
(1984, 12, 3, 'Bhopal disaster', 'Gas leak kills thousands in India', 'Disasters'),
(1674, 12, 4, 'Father Marquette founds Chicago', 'Explorer establishes settlement', 'Exploration'),
(1991, 12, 4, 'Pan Am ceases operations', 'Airline shuts down', 'Business'),
(1492, 12, 5, 'Columbus discovers Hispaniola', 'Explorer reaches Caribbean island', 'Exploration'),
(1933, 12, 5, 'Prohibition ends', '21st Amendment ratified', 'Politics'),
(1917, 12, 6, 'Finland declares independence', 'Independence from Russia', 'Politics'),
(1989, 12, 6, 'Marc Lépine massacre', 'Anti-feminist shooting in Montreal', 'Disasters'),
-- December 7 covered
(1941, 12, 8, 'US enters World War II', 'Congress declares war on Japan', 'Military'),
(1980, 12, 8, 'John Lennon killed', 'Beatles musician shot in New York', 'Music'),
(1905, 12, 9, 'Separation of church and state', 'French law enacted', 'Politics'),
(1979, 12, 9, 'Smallpox eradicated', 'WHO declares disease eliminated', 'Medicine'),
(1901, 12, 10, 'First Nobel Prizes awarded', 'Inaugural Nobel ceremony', 'Society'),
(1948, 12, 10, 'Universal Declaration of Human Rights', 'UN adopts human rights declaration', 'Politics'),
(1931, 12, 11, 'Statute of Westminster', 'British Commonwealth established', 'Politics'),
(1994, 12, 11, 'First Chechen War begins', 'Russia invades Chechnya', 'Military'),
(1800, 12, 12, 'Washington DC becomes capital', 'Federal government relocates', 'Politics'),
(1963, 12, 12, 'Kenya independence', 'East African nation gains independence', 'Politics'),
(1577, 12, 13, 'Drake begins circumnavigation', 'Explorer starts voyage', 'Exploration'),
(2003, 12, 13, 'Saddam Hussein captured', 'Iraqi dictator found hiding', 'Military'),
(1911, 12, 14, 'Amundsen reaches South Pole', 'Norwegian explorer first to pole', 'Exploration'),
(2012, 12, 14, 'Sandy Hook shooting', 'School massacre in Connecticut', 'Disasters'),
(1791, 12, 15, 'Bill of Rights ratified', 'First 10 amendments to Constitution', 'Politics'),
(1939, 12, 15, 'Gone with the Wind premieres', 'Epic film debuts in Atlanta', 'Entertainment'),
(1773, 12, 16, 'Boston Tea Party', 'Colonists dump tea in harbor', 'Politics'),
(1944, 12, 16, 'Battle of the Bulge begins', 'Last major German offensive', 'Military'),
-- December 17 covered
(1865, 12, 18, '13th Amendment ratified', 'Slavery abolished in United States', 'Politics'),
(1972, 12, 18, 'Operation Linebacker II', 'US bombs Hanoi', 'Military'),
(1776, 12, 19, 'The Crisis published', 'Thomas Paine publishes pamphlet', 'Politics'),
(1998, 12, 19, 'Clinton impeached', 'President impeached by House', 'Politics'),
(1860, 12, 20, 'South Carolina secedes', 'First state leaves Union', 'Politics'),
(1989, 12, 20, 'US invades Panama', 'Operation Just Cause begins', 'Military'),
(1620, 12, 21, 'Plymouth Rock', 'Pilgrims land at Plymouth', 'Exploration'),
(1968, 12, 21, 'Apollo 8 orbits Moon', 'First humans orbit Moon', 'Space'),
(1956, 12, 22, 'Colo born', 'First gorilla born in captivity', 'Science'),
(1989, 12, 22, 'Romanian Revolution', 'Ceaușescu regime falls', 'Politics'),
(1913, 12, 23, 'Federal Reserve created', 'Central banking system established', 'Economics'),
(1986, 12, 23, 'Voyager around the world', 'Aircraft completes non-stop flight', 'Aviation'),
(1814, 12, 24, 'Treaty of Ghent signed', 'War of 1812 officially ends', 'Politics'),
(1968, 12, 24, 'Apollo 8 Earthrise photo', 'Iconic photo of Earth from Moon', 'Space'),
-- December 25 covered
-- December 26 covered
(1831, 12, 27, 'Darwin begins Beagle voyage', 'Naturalist starts expedition', 'Exploration'),
(1979, 12, 27, 'Soviet invasion of Afghanistan', 'USSR invades Afghanistan', 'Military'),
(1832, 12, 28, 'John C. Calhoun resigns', 'First VP to resign', 'Politics'),
(1973, 12, 28, 'Endangered Species Act', 'US wildlife protection law signed', 'Politics'),
(1170, 12, 29, 'Thomas Becket murdered', 'Archbishop killed in Canterbury Cathedral', 'Religion'),
(1890, 12, 29, 'Wounded Knee Massacre', 'US troops kill Lakota Sioux', 'Military'),
-- December 30 covered
(1943, 12, 31, 'Allied leaders at Tehran', 'Roosevelt, Churchill, Stalin meet', 'Politics'),
(1999, 12, 31, 'Panama Canal handover', 'US transfers canal to Panama', 'Politics');

SELECT '✓ FULL YEAR COVERAGE COMPLETE!' AS Status;
SELECT COUNT(*) AS total_events FROM events;
SELECT COUNT(DISTINCT CONCAT(month,'-',day)) AS unique_dates_covered FROM events;
SELECT (366 - COUNT(DISTINCT CONCAT(month, '-', day))) AS dates_still_missing FROM events;
